steps:
  - name: build-hugo
    image: hugomods/hugo:exts
    when:
      - event: push
        branch: main
      - event: manual
    volumes:
      - /home/rick/blogs/doityourblog/public:/blog/public
    environment:
      HUGO_CMD: "hugo"
    commands:
      - cp /woodpecker/src/github.com/r1ckhdk/doityourblog /blog
      - cd /blog
      - $HUGO_CMD build
