when:
  - event: push
    branch: main
  - event: manual

steps:
  - name: build
    image: hugomods/hugo:exts
    commands:
      - hugo build

  - name: deploy
    image: alpine
    volumes:
      - /home/rick/blogs/doityourblog/public:/deploy
    commands:
      - rm -rf /deploy/*
      - cp -r public/* /deploy/
