when:
  - event: push
    branch: main
  - event: manual

steps:
  - name: build-and-deploy
    image: hugomods/hugo:exts
    volumes:
      - /home/rick/blogs/doityourblog:/blog
    environment:
      HUGO_CMD: "hugo"
    commands:
      - cd /blog
      - $HUGO_CMD build
